FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip

ADD ./* /app/

WORKDIR /app

RUN cd /app

RUN pip3 install numpy
RUN pip3 install -r requirements.txt

EXPOSE 5000/tcp

CMD python3 service.py
